# frozen_string_literal: true

module Pdfrb
  class Document
    # Facade for AcroForm interactive forms (ISO 32000-2 §12.7).
    #
    # Creates the /AcroForm dictionary on the Catalog and manages
    # form fields. Each field is a /Type /Annot /Subtype /Widget
    # indirect object linked to a page via /P and positioned via /Rect.
    #
    # Supported field types (FT):
    #   :Btn — button (checkbox, radio, pushbutton)
    #   :Tx  — text input
    #   :Ch  — choice (list, combo)
    #   :Sig — digital signature
    #
    # Appearance streams are generated by the viewer when /NeedAppearances
    # is true on the /AcroForm dict.
    class Form
      attr_reader :document

      def initialize(document)
        @document = document
      end

      # Enable AcroForm by creating the /AcroForm dict on the Catalog.
      # Idempotent. @return [Hash] the AcroForm dict value.
      def enable!
        catalog = document.catalog
        return catalog.value[:AcroForm] if catalog.value[:AcroForm]

        acroform = {
          Fields: [],
          NeedAppearances: true,
          DA: "/Helv 0 Tf 0 g",
        }
        catalog.value[:AcroForm] = acroform
        acroform
      end

      # Add a text field. @return [Pdfrb::Model::Cos::Dictionary] the field.
      def add_text_field(name, page:, rect:, value: nil, multiline: false)
        enable!
        flags = 0
        flags |= 0x1000 if multiline # bit 13 = multiline

        field = build_widget(name, page: page, rect: rect)
        field.value[:FT] = :Tx
        field.value[:Ff] = flags if flags.positive?
        field.value[:V] = value if value
        register_field(field)
        field
      end

      # Add a checkbox field. @return [Pdfrb::Model::Cos::Dictionary] the field.
      def add_checkbox(name, page:, rect:, checked: false)
        enable!
        field = build_widget(name, page: page, rect: rect)
        field.value[:FT] = :Btn
        field.value[:V] = checked ? :Yes : :Off
        register_field(field)
        field
      end

      # Add a combo box (dropdown) field.
      # @return [Pdfrb::Model::Cos::Dictionary] the field.
      def add_combo(name, page:, rect:, options:, value: nil)
        enable!
        field = build_widget(name, page: page, rect: rect)
        field.value[:FT] = :Ch
        field.value[:Ff] = 0x20000 # bit 18 = Combo
        field.value[:Opt] = options
        field.value[:V] = value if value
        register_field(field)
        field
      end

      # Total field count.
      def count
        acroform = document.catalog.value[:AcroForm]
        return 0 unless acroform

        fields = acroform[:Fields]
        fields ? fields.length : 0
      end

      # Find a field by fully qualified name.
      def find(name)
        each_field.find { |f| f.value[:T] == name }
      end

      # Enumerate all top-level fields.
      def each_field(&block)
        acroform = document.catalog.value[:AcroForm]
        return enum_for(:each_field) unless block

        return unless acroform

        fields = acroform[:Fields] || []
        fields.each do |ref|
          obj = ref.is_a?(Pdfrb::Model::Reference) ? document.object(ref) : ref
          yield obj if obj
        end
      end

      private

      def build_widget(name, page:, rect:)
        widget = document.add(
          {
            Type: :Annot,
            Subtype: :Widget,
            T: name,
            Rect: rect,
            P: Pdfrb::Model::Reference.new(page.oid, page.gen),
            FT: :Tx,
          },
          type: Pdfrb::Model::Type::Annotation
        )
        add_annot_to_page(page, widget)
        widget
      end

      def add_annot_to_page(page, widget)
        annots = page.value[:Annots]
        ref = Pdfrb::Model::Reference.new(widget.oid, widget.gen)
        if annots.nil?
          page.value[:Annots] = [ref]
        elsif annots.is_a?(::Array)
          annots << ref
        else
          page.value[:Annots] = [annots, ref]
        end
      end

      def register_field(field)
        acroform = document.catalog.value[:AcroForm]
        fields = acroform[:Fields]
        ref = Pdfrb::Model::Reference.new(field.oid, field.gen)
        fields << ref
      end
    end
  end
end
