# frozen_string_literal: true

module Pdfrb
  autoload :VERSION, "pdfrb/version"

  autoload :Error, "pdfrb/error"
  autoload :ParseError, "pdfrb/error"
  autoload :LexError, "pdfrb/error"
  autoload :SyntaxError, "pdfrb/error"
  autoload :MalformedPdfError, "pdfrb/error"
  autoload :SerializeError, "pdfrb/error"
  autoload :FilterError, "pdfrb/error"
  autoload :EncryptionError, "pdfrb/error"
  autoload :UnsupportedVersionError, "pdfrb/error"
  autoload :ValidationError, "pdfrb/error"
  autoload :ObjectReferenceError, "pdfrb/error"

  autoload :Configuration, "pdfrb/configuration"
  autoload :DataDir, "pdfrb/data_dir"
  autoload :PdfConstants, "pdfrb/pdf_constants"

  autoload :Source, "pdfrb/source"
  autoload :Model, "pdfrb/model"
  autoload :Arlington, "pdfrb/arlington"
  autoload :Filter, "pdfrb/filter"
  autoload :Content, "pdfrb/content"
  autoload :Encryption, "pdfrb/encryption"
  autoload :DigitalSignature, "pdfrb/digital_signature"

  require "pdfrb/model/type/file_trailer"
  require "pdfrb/model/type/catalog"
  require "pdfrb/model/type/info"
  require "pdfrb/model/type/page_tree_node"
  require "pdfrb/model/type/page"
  require "pdfrb/model/type/resources"
  require "pdfrb/model/type/metadata"
  require "pdfrb/model/type/object_stream"
  require "pdfrb/model/type/xref_stream"
  require "pdfrb/model/type/graphics_state_parameter"
  require "pdfrb/model/type/optional_content_group"
  require "pdfrb/model/type/struct_tree_root"
  require "pdfrb/model/type/font_type1"
  require "pdfrb/model/type/annotation"
  require "pdfrb/model/type/mark_information"
  require "pdfrb/model/type/icon_fit"
  require "pdfrb/model/type/page_label"
  require "pdfrb/model/type/action_goto"
  require "pdfrb/model/type/action_uri"
  require "pdfrb/model/type/action_launch"
  require "pdfrb/model/type/action_java_script"
  require "pdfrb/model/type/marked_content_reference"
  require "pdfrb/model/type/namespace"
  require "pdfrb/model/type/optional_content_config"
  require "pdfrb/model/type/markup_annotation"
  require "pdfrb/model/type/link_annotation"
  require "pdfrb/model/type/text_annotation"
  require "pdfrb/model/type/stamp_annotation"
  require "pdfrb/model/type/circle_annotation"
  require "pdfrb/model/type/square_annotation"
  require "pdfrb/model/type/ink_annotation"
  require "pdfrb/model/type/line_annotation"
  require "pdfrb/model/type/polygon_annotation"
  require "pdfrb/model/type/polyline_annotation"
  require "pdfrb/model/type/widget_annotation"
  require "pdfrb/model/type/form_field"
  require "pdfrb/model/type/document_security_store"
  require "pdfrb/model/type/measure"
  require "pdfrb/model/type/border_styling"
  require "pdfrb/model/type/appearance_generator"
  require "pdfrb/model/type/border_effect"
  require "pdfrb/model/type/line_ending_styling"
  require "pdfrb/model/type/interior_color"
  require "pdfrb/model/type/object_reference"
  require "pdfrb/model/type/square_circle"
  require "pdfrb/model/type/variable_text_field"
  require "pdfrb/model/type/action_go_to_r"
  require "pdfrb/model/type/action_set_ocg_state"
  require "pdfrb/model/type/viewer_preferences"
  require "pdfrb/model/type/action"

  autoload :Font, "pdfrb/font"
  autoload :FontLoader, "pdfrb/font_loader"
  autoload :FontResolver, "pdfrb/font_resolver"
  autoload :ImageLoader, "pdfrb/image_loader"
  autoload :Task, "pdfrb/task"
  autoload :Color, "pdfrb/color"
  autoload :Annotation, "pdfrb/annotation"
  autoload :Appearance, "pdfrb/appearance"
  autoload :Conformance, "pdfrb/conformance"
  autoload :Validator, "pdfrb/validator"
  autoload :XMP, "pdfrb/xmp"
  autoload :Destination, "pdfrb/destination"
  autoload :Linearization, "pdfrb/linearization"
  autoload :Action, "pdfrb/action"

  autoload :Serializer, "pdfrb/serializer"
  autoload :Writer, "pdfrb/writer"
  autoload :Importer, "pdfrb/importer"
  autoload :Revision, "pdfrb/revision"
  autoload :Revisions, "pdfrb/revisions"
  autoload :XrefSection, "pdfrb/xref_section"
  autoload :Document, "pdfrb/document"

  autoload :Compare, "pdfrb/compare"
  autoload :CLI, "pdfrb/cli"
  require "logger"

  def self.logger
    @logger ||= Logger.new($stderr, level: Logger::WARN)
  end

  def self.logger=(log)
    @logger = log
  end
end
